global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "192.168.67.4:9100"
          - "192.168.67.5:9100"
          - "192.168.67.6:9100"
          - "192.168.67.7:9100"

  - job_name: "postgres_exporter"
    static_configs:
      - targets:
          - "192.168.67.6:9187"
          - "192.168.67.7:9187"

