all:
  hosts:
    docker01:
      ansible_host: 192.168.67.4
    etcd01:
      ansible_host: 192.168.67.5
    pgsql01:
      ansible_host: 192.168.67.6
    pgsql02:
      ansible_host: 192.168.67.7
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

