---
- name: Download etcd binary
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/v3.5.17/etcd-v3.5.17-linux-arm64.tar.gz"
    dest: "/tmp/etcd-v3.5.17-linux-arm64.tar.gz"
    mode: '0644'

- name: Extract etcd binary
  unarchive:
    src: "/tmp/etcd-v3.5.17-linux-arm64.tar.gz"
    dest: "/tmp/"
    remote_src: yes
    creates: "/tmp/etcd-v3.5.17-linux-arm64"

- name: Move etcd binary to /usr/local/bin
  command:
    cmd: mv /tmp/etcd-v3.5.17-linux-arm64/etcd /usr/local/bin/etcd
    creates: "/usr/local/bin/etcd"

- name: Set correct permissions for etcd binary
  file:
    path: "/usr/local/bin/etcd"
    mode: '0755'

- name: Create etcd service user
  user:
    name: etcd
    system: yes
    state: present

- name: Create etcd service directory
  file:
    path: "/etc/etcd"
    state: directory
    owner: etcd
    group: etcd
    mode: '0755'

- name: Create etcd configuration file from template
  template:
    src: "etcd.conf.j2"
    dest: "/etc/etcd/etcd.conf"
    owner: etcd
    group: etcd
    mode: '0644'

- name: Create systemd service for etcd
  copy:
    content: |
      [Unit]
      Description=etcd
      Documentation=https://github.com/etcd-io/etcd
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/etcd --config-file /etc/etcd/etcd.conf
      Restart=always
      User=etcd
      Group=etcd
      LimitNOFILE=40000
      TimeoutStartSec=0

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/etcd.service"
    owner: root
    group: root
    mode: '0644'

- name: Enable and start etcd service
  systemd:
    name: etcd
    enabled: yes
    state: started

