global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "192.168.18.87:9100"
          - "192.168.18.83:9100"
          - "192.168.18.84:9100"
          - "192.168.18.85:9100"

  - job_name: "postgres_exporter"
    static_configs:
      - targets:
          - "192.168.18.84:9187"
          - "192.168.18.85:9187"