---
- name: Install Docker on docker01
  hosts: docker01
  become: true
  tasks:
    - name: Install prerequisites
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Add Docker repository
      yum_repository:
        name: docker-ce
        description: Docker CE Stable Repository
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        enabled: 1
        gpgcheck: 1
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Enable aarch64 repository
      lineinfile:
        path: /etc/yum.repos.d/docker-ce.repo
        regexp: '^#basearch='
        line: 'basearch=aarch64'
        state: present

    - name: Install Docker
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
