---
- name: Add PostgreSQL repository without GPG check
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-aarch64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
    disable_gpg_check: true
  become: true

- name: Disable default PostgreSQL module
  command: "dnf -qy module disable postgresql"
  args:
    warn: false
  become: true

- name: Install PostgreSQL server
  yum:
    name: postgresql{{ pgsql_version }}-server
    state: present
    disable_gpg_check: true
  become: true

- name: Initialize PostgreSQL database
  command: "/usr/pgsql-{{ pgsql_version }}/bin/postgresql-{{ pgsql_version }}-setup initdb"
  become: true

- name: Enable PostgreSQL service
  systemd:
    name: postgresql-{{ pgsql_version }}
    enabled: true
    state: started
  become: true

