- name: Create test_user
  postgresql_user:
    name: test_user
    password: "{{ test_user_password }}"
    priv: "CONNECT"

- name: Create test_db1
  postgresql_db:
    name: test_db1
    owner: test_user

- name: Allow test_user to connect from any host
  lineinfile:
    path: /var/lib/pgsql/{{ pgsql_version }}/data/pg_hba.conf
    line: "host    test_db1    test_user    0.0.0.0/0    md5"
    state: present

- name: Create monitoring user
  postgresql_user:
    name: svc_monitoring
    password: "{{ monitoring_user_password }}"
    priv: "SELECT"

